lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET_KEY)%' # Use your secret key here
    public_key: '%env(JWT_PUBLIC_KEY)%' # If you're using public/private key pair
    pass_phrase: '%env(PASSPHRASE)%' # If your key is passphrase protected
    token_ttl: 3600 # Token expiration time in seconds
